### ISSUE TITLE
Please Help (Ragnarok Openkore Config)

### ISSUE THREAD

**Issue by rgiro01** [PipeDeveloper/PipeDeveloper.github.io#1]
Good Afternoon!

Three of my bots were warped on different maps where they couldn't get out. Do you know a specific config to use butterfly wing or Eden Mark whenever they are warped by GMs or someone? Thank you.

**Comment by PipeDeveloper** [comment]
Try a simple macro on your control folder.

```
automacro warpped {
	location not pay_fild01 #Change this to your botting map
        location not payon #Change this to your botting map
        location not pay_in01 #Change this to your botting map
	timeout 60
	      call {
              do is Butterfly Wing
        }
}
```

In summary, if you are not on those maps, then you will use a Butterfly Wing to go back to town, and macro re-starts every 1 minute (this is if the warpping person places the warp on the respawn cell).
Hope this help you to have an idea to make a macro more complete

**Comment by PipeDeveloper** [comment]
Closed
